### ISSUE TITLE
roll_eigen

### ISSUE THREAD

**Issue by ckatsulis** [jjf234/roll#15]
Are you able to continue to include the roll_eigen function?  I have found it useful and would like to continue to update the package with new enhancements and changes without losing this functionality.

Thanks.

**Comment by ckatsulis** [comment]
Furthermore, when I go to reinstall the prior version via:
`install_version("roll", version = "1.0.7", repos = "http://cran.us.r-project.org")`

I receive this error:

```
Error in get(method, envir = home) : 
  lazy-load database '/home/xxxxxxxxx/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/R/Rcpp.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
```

**Comment by jjf234** [comment]
I removed less common functions in order to focus on addressing a few missing gaps (see #4 and #13), but also because the roll package already does the heavy-lifting to get you the inputs for what you need to use in another function. Specifically, you can run `eigen` on the outputs from `roll_cov`. For example, load `roll_eigen` from [roll_extra.txt](https://github.com/jjf234/roll/files/2498205/roll_extra.txt) and then run:
```
library(roll)
library(xts)

# dummy data
n_vars <- 3
n_obs <- 15
dates <- seq(Sys.Date(), by = "day", length.out = n_obs)
x <- xts(matrix(rnorm(n_obs * n_vars), nrow = n_obs, ncol = n_vars), dates)
colnames(x) <- paste0("Ticker", 1:n_vars)

# example
result <- roll_eigen(x, width = 5)
```

I'm not able to replicate the `Rcpp` error message on my side but a quick search of the error message turned up a promising lead: https://github.com/wch/movies/issues/3. Try restarting R or uninstalling and reinstalling `Rcpp`.

**Comment by ckatsulis** [comment]
Thanks for your reply.  I will try the other roll_eigen call.

Best,

Chris

**Comment by jjf234** [comment]
No problem, please feel free to reopen if needed.
