### ISSUE TITLE
Weighting in roll_sum

### ISSUE THREAD

**Issue by grlju** [jjf234/roll#21]
I am trying to calculate a rolling sum with weights but I cannot make sense of the results I am getting. 

`roll_sum(as.matrix(c(1, 0, 0, 0)), width = 4, weights = c(0.5, 0.3, 0.2, 0.1), min_obs = 1, online = FALSE)
`

I expected this: `0.5, 0.8, 1.0, 1.1`

Is this a bug or am I missunderstanding how the weighting works?

I asked this question here to no avail: https://stackoverflow.com/questions/57737496/how-does-the-weighting-in-the-roll-package-work-exactly

**Comment by jjf234** [comment]
The easiest way to understand the computation is to first look at the results for the "full window," i.e. the last output in the example:

```
x <- c(1, 0, 0, 0)
weights <- c(0.5, 0.3, 0.2, 0.1)

> sum(x * weights)
[1] 0.5
```

When I roll the function above, the test case matches the behavior of the `roll_sum` function as intended:

```
library(roll)
library(testthat)
library(xts)

r_sum <- function(x, weights) {
  sum(x * weights)
}

> expect_equivalent(roll_sum(as.matrix(x), 4, weights, online = FALSE),
+                   rollapplyr(x, 4, r_sum, weights = weights, fill = NA))
```

Otherwise,  since `min_obs = 1` in the example, the window size of first three results is expanding from oldest to newest until the row is the same size of `width` like the test case above (note: the order of `weights` is also expected to be from oldest to newest, which is consistent with other functions in R). Specifically:

- First window (`width = 1`): 0.1 (= 0.1 * 1)
- Second window (`width = 2`): 0.2 (= 0.1 * 0 + 0.2 * 1)
- Third window (`width = 3`): 0.3 (= 0.1 * 0 + 0.2 * 0 + 0.3 * 1)
- Fourth window (`width = 4`): 0.5 (= 0.1 * 0 + 0.2 * 0 + 0.3 * 0 + 0.5 * 1), which is the same as `sum(x * weights)`

**Comment by grlju** [comment]
Thank you for the explanation! It clarifies the result. 

I was not aware that the weights would be applied from oldest to newest and assumed (wrongly) that the `min_obs` argument would imply some sort of recursion rather than an expanding window.
