### ISSUE TITLE
Does roll_quantile have an "online" algorithm?

### ISSUE THREAD

**Issue by AndreMikulec** [jjf234/roll#34]
Hi,

(1) I noticed that you said.

Version 1.1.5

New roll_quantile function for computing rolling and expanding quantiles of time-series data
Note: roll_quantile function is not calculated using an online algorithm
in
https://cran.r-project.org/web/packages/roll/news/news.html

(2) I noticed that exists the function:
RollQuantileOfflineVec
And *does not exist* the function:
RollQuantileOnlineVec
in
DEC 2020
https://github.com/jjf234/roll/blob/b640085a6af337ed150ef869b588880009f54038/src/roll_vec.h

(3) I noticed that roll_quantile has an option "online"

roll_quantile(x, width, weights = rep(1, width), p = 0.5,
min_obs = width, complete_obs = FALSE, na_restore = FALSE,
online = FALSE)

online logical. Process observations using an online algorithm
in
https://cran.r-project.org/web/packages/roll/roll.pdf

So, does roll_quantile have an "online" algorithm (or not)?

Thanks,

Andre Mikulec

**Comment by jjf234** [comment]
The `roll_quantile` function does not offer an online algorithm, so that is why the note was included in the news file. Function arguments (and naming conventions in the underlying source code) are consistent across the `roll` package so that is also why `online` is included and set to `FALSE`. For background, I want to be explicit to the user especially as the default for other functions is `TRUE`. Lastly, `roll_quantile` will throw a warning if `online = TRUE`. Hope that helps.

**Comment by AndreMikulec** [comment]
Thanks.
