### ISSUE TITLE
roll_eigen

### ISSUE THREAD

**Issue by nassuphis** [jjf234/roll#35]
hello, I noticed that this function was removed, its a pity it is quite useful to have
NN

**Comment by jjf234** [comment]
I removed less common functions in order to focus on addressing missing gaps, but also because the roll package already does the heavy-lifting to get you the inputs for what you need to use in another function. Specifically, you can run `eigen` on the outputs from `roll_cov`. For example, load `roll_eigen` from [roll_extra.txt](https://github.com/jjf234/roll/files/2498256/roll_extra.txt) and then run:
```
library(roll)
library(xts)

# dummy data
n_vars <- 3
n_obs <- 15
dates <- seq(Sys.Date(), by = "day", length.out = n_obs)
x <- xts(matrix(rnorm(n_obs * n_vars), nrow = n_obs, ncol = n_vars), dates)
colnames(x) <- paste0("Ticker", 1:n_vars)

# example
result <- roll_eigen(x, width = 5)
```
